import 'bootstrap/dist/css/bootstrap.css';
import BootstrapClient from '../components/BootstrapClient.js';
import { nunito_sans } from './utils/fonts';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito_sans}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
